# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=30)),
                ('periododescanso', models.CharField(max_length=20)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('citafecha', models.DateTimeField(null=True)),
                ('aministracion', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tratamientos',
                'verbose_name': 'Tratamiento',
            },
        ),
    ]
