# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0003_auto_20161104_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('historialmedic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.Historialmedic')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
    ]
