# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0004_antecedente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoact', models.TextField(blank=True, null=True)),
                ('examfis', models.TextField(blank=True, null=True)),
                ('historialmedic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.Historialmedic')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
                'verbose_name': 'Consulta',
            },
        ),
    ]
