# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topico', '0005_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(blank=True, max_length=60, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topico.Consulta')),
            ],
            options={
                'verbose_name': 'Derivacion',
                'verbose_name_plural': 'Derivacions',
            },
        ),
    ]
